
install:
  stage: build
  image: dalibo/temboard-agent
  script:
  - bash share/docker/init_temboardagent_with_pgbadger.sh

api_test:
  stage: test
  image: dalibo/temboard-agent
  script:
  - make api_pgbadger_version    
