
image: python:latest

stages:
  - prepare
  - build
  - test
  - deploy

install_pgbadger:
  stage: prepare
  script: 
  #- apt-get update && apt-get install -y git bzip2
  - make pytest_prepare
  artifacts:
    paths:
    - _tmp/
    - src/
    expire_in: 1 hour

install:
  stage: build
  image: dalibo/temboard-agent
  script:
  - bash share/docker/init_temboardagent_with_pgbadger.sh
  when: manual      

api_test:
  stage: test
  image: dalibo/temboard-agent
  script:
  - make api_pgbadger_version
  when: manual    

unit-latest:
  stage: test
  image: python:latest
  script:
  - apt-get update && apt-get install -y libjson-xs-perl
  - pip install -r tests/unit/requirements.txt
  - python -m pytest --cov=pgbadger tests/unit/
  # Python 3.6 is not officially supported yet
  when: manual 

unit-2.7:
  stage: test
  image: python:2.7
  script:
  - apt-get update && apt-get install -y libjson-xs-perl
  - pip install -r tests/unit/requirements.txt 
  - make pytest
