


install:
  stage: build
  image: dalibo/temboard-agent
  script:
  - bash share/docker/init_temboardagent_with_pgbadger.sh
  when: manual      

api_test:
  stage: test
  image: dalibo/temboard-agent
  script:
  - make api_pgbadger_version
  when: manual    

unit-2.7:
  stage: test
  image: python:2.7
  script:
  - pip install -r requirements.txt 
  - python -m pytest tests/unit/
