version: '2'

volumes:
  data:
  run:

services:
  repository:
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: temboard
      POSTGRES_PASSWORD: temboard
    labels:
      com.dnsdock.alias: postgres.temboard.docker

  ui:
    image: dalibo/temboard:latest
    links:
      - repository
    environment:
      PGHOST: repository
      PGUSER: temboard
      PGPASSWORD: temboard
    ports:
      - "8889:8888"
    labels:
      com.dnsdock.alias: www.temboard.docker

  instance:
    image: postgres:10-alpine
    volumes:
      - data:/var/lib/postgresql/data
      - run:/var/run/postgresql
    labels:
      com.dnsdock.alias: instance.temboard.docker

  agent:
    image: dalibo/temboard-agent
    environment:
      HISTFILE: /usr/local/src/temboard-agent/docker-histfile
      TEMBOARD_UI_URL: https://ui:8889/
      TEMBOARD_HOSTNAME: instance.fqdn
      TEMBOARD_KEY: key_for_agent_dev
      TEMBOARD_SSL_CA: /usr/local/src/temboard-agent/share/temboard-agent_ca_certs_CHANGEME.pem
      TEMBOARD_SSL_CERT: /usr/local/src/temboard-agent/share/temboard-agent_CHANGEME.pem
      TEMBOARD_SSL_KEY: /usr/local/src/temboard-agent/share/temboard-agent_CHANGEME.key
    ports:
      - "2345:2345"        
    volumes:
      - data:/var/lib/postgresql/data 
      - run:/var/run/postgresql/:ro
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/usr/local/src/temboard-agent/
    links:
      - instance:instance.fqdn
#    command: tail -f /dev/null
    labels:
      com.dnsdock.alias: agent.temboard.docker
